let hasSuperPowers;
hasSuperPowers = true;
hasSuperPowers = false;
hasSuperPowers = Boolean(0);
hasSuperPowers = Boolean(1);
hasSuperPowers = !!'true';
hasSuperPowers = !!'';
// console.log(hasSuperPowers);
let heightInCM = 188;
heightInCM = Number(true);
heightInCM = Number('188');
heightInCM = +('188');
heightInCM = +(false);
let hero;
hero = "Batman";
hero = String(122);
hero = String(true);
hero = (122).toString();
console.log(hero);
export {};
