var hasSuperPowers;
hasSuperPowers = true;
hasSuperPowers = false;
hasSuperPowers = Boolean(0);
hasSuperPowers = Boolean(1);
hasSuperPowers = Boolean('true');
hasSuperPowers = !!'true';
hasSuperPowers = !!'';
// console.log(hasSuperPowers);
var heightInCm = 188;
heightInCm = Number(true);
heightInCm = Number('188');
heightInCm = +('188');
heightInCm = +(true);
// console.log(heightInCm);
var hero;
hero = 'batman';
hero = String(122);
hero = String(true);
hero = (122).toString();
console.log(hero);
